# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d2e73fa5556a76d866965a64c0b2237b2980e4e3012050181c70d1d8842d0d208af4c13799aeaefe239575e214bfeedf3e3d82f7434a8399527d5b5c229ef6

test:
  secret_key_base: 25b1bc131bcde1955062bd8eefb20a613db3b0f4afd84a86fce715eba6134431b894747bfbf89e8a43eb493b07a117acfea8924b609e21b2ce03451c4d7f0c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
